builds:
  - 
    binary: mosquitto_mqtt_exporter

    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - linux

    goarch:
      - amd64
      - arm64
      - arm
      - 386

    goarm:
      - 5
      - 6
      - 7

release:

  draft: true

  # prerelease: true

  discussion_category_name: Announcements
  
  header: |
    ## Prometheus exporter for Mosquitto mqtt broker
    ### Release {{ .Tag }}  ({{ .Date }})


checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'