name: Publish-GHRC

on:
  workflow_run:
    branches: [ master ]
    workflows: ["Go-Build"]
    types:
      - completed

jobs:
  Publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$( curl -s  https://api.github.com/repos/RizkyRajitha/mosquitto_mqtt_exporter/tags | jq '.[0].name' | sed 's/\"//g')"

      - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}

      - name: Checkout repository with latest tag
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}

      - name: Build docker container
        run: docker build . -t ghcr.io/$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')/mosquitto_mqtt_exporter:${{ steps.latestrelease.outputs.releasetag }} -t ghcr.io/$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')/mosquitto_mqtt_exporter:latest  -t ghcr.io/$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')/mosquitto_mqtt_exporter:$(echo $GITHUB_SHA | head -c7)

      - name: Login to docker
        run: echo  ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Push
        run: docker push ghcr.io/$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')/mosquitto_mqtt_exporter:latest
