name: Release

on:
  workflow_run:
    branches: [ master ]
    workflows: ["Go-Build"]
    types:
      - completed

jobs:
  Release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$( curl -s  https://api.github.com/repos/RizkyRajitha/mosquitto_mqtt_exporter/tags | jq '.[0].name' | sed 's/\"//g')"

      - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}

      - name: tagcheckout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
